### ISSUE TITLE
imx6 vpu/ipu elements causing visual distortions 

### ISSUE THREAD

**Issue by Donnyp751** [Freescale/libimxvpuapi#52] opened 2022-12-08 03:38 UTC
Hello,
I have been attempting to upgrade to versions > 0.10.3, but am running into an issue with visual distortions and a green strip across the bottom 50-100 pixels of the image after encoding. I can take a snapshot of a raw image from the source element prior to being encoded and they look perfect, but after encoding a 1920x1080 image it has bad distortions in it's color, and a green strip across the bottom. This does not happen when scaling the image down prior to encoding to sizes below 1920x1024 (1024 with seems to be special or related to the issue). This occurs on all versions newer then 0.10.3.  

Here is the pipeline I have been using for testing
In 0.10.3 I can get 1920x1080 @ 30 fps with perfect image quality 
gst-launch-1.0 -v imxv4l2videosrc imx-capture-mode=5 ! video/x-raw,width=1920,height=1080 ! imxipuvideotransform ! video/x-raw,width=1920,height=1080  ! imxvpuenc_h264 bitrate=5000 ! rtph264pay ! queue ! udpsink host=192.168.210.26 port=5004

But after that using this pipeline I get bad visual effects 
1920x1080 @ 30 fps with a green strip on the bottom and visual distortions
gst-launch-1.0 -v imxv4l2videosrc ! video/x-raw,width=1920,height=1080,format=I420 ! imxipuvideotransform ! video/x-raw,width=1920,height=1080  ! imxvpuenc_h264 bitrate=5000 ! rtph264pay ! udpsink host=192.168.210.26 port=5004

With newer versions this pipeline doesn't have the bad visual effects
1536 x 1024 @ 25 fps
 gst-launch-1.0 -v imxv4l2videosrc ! video/x-raw,width=1920,height=1080,format=NV12 ! imxipuvideotransform ! video/x-raw,width=1536,height=1024  ! imxvpuenc_h264 bitrate=5000 ! rtph264pay ! udpsink host=192.168.210.26 port=5004

many other combinations of resolutions resulted in green strips, and unrecognizable images.

I'm not sure if this issue belongs on here, or on the gst-imx plugin itself as I have not been able to isolate which one is causing it considering they must be updated together 

The system I'm working on is an IMX6Q running linux 4.x

**Comment by dv1** [comment] 2022-12-08 06:03
Can you verify if the old 0.10.3 pipeline uses I420 or NV12 as the pixel format?

And:

> many other combinations of resolutions resulted in green strips, and unrecognizable images

What pixel formats were used in these combinations?

**Comment by Donnyp751** [comment] 2022-12-08 15:09
The old 0.10.3 pipeline is using I420. 

With the new pipeline I had the best results with I420, and NV12 but both had the green strip on the bottom.

new pipeline with different pixel formats  1920 x 1080 
UYVY had bad visual distortion and ran @ 20fps
NV12 had bad visual distortion and ran @ 30fps
I420 had bad visual distortion and ran @ 30fps
YUY2 had bad visual distortion and ran @ 20fps

As long as I left at 1920 x 1080 The images were recognizable from the above pixel formats, but with color distortion and a green strip 50-100 pixels high across the bottom.

BGRA,BGRx,BGR,RGB,RGB16,YV12,Y42B had an internal datastream error
RGBA,ABGR,Y444,v308 doesn't work with source

**Comment by dv1** [comment] 2022-12-10 22:00
I'm on it. Seems to be caused by plane offset bugs, which in turn are related to video meta not being produced and/or processed correctly.

**Comment by Donnyp751** [comment] 2022-12-11 05:22
Great! On a potentially unrelated note, do you know what is the proper way to run dual video streams while keeping it in hardware. I'm trying to have a imxv4l2videosrc connected to a tee to two different imxipuvideotransform => imxvpuenc_h264.
It seems like once there is two paths from a tee off the video source some copying may occur on the cpu as the framerate drops from 30fps with one set off the tee, but once I put the second path onto the tee the fps drops to 17-18 fps. cpu usage isn't really high either so it seems like something is getting bottle necked and limited by cpu. Not sure if maybe the tee isn't done in the hardware/DMA or what is the proper way to go about it. I'm trying to have two different resolutions going to a separate video encoders, then later network sinks. From the testing I've done it seems like the bottle neck is between the video source and the encoders, but I'm having a hard time figuring out how to get around the issue.

**Comment by dv1** [comment] 2022-12-16 17:54
I got a lead. In `imx_vpu_api_enc_open()` in `imxvpuapi2/imxvpuapi2_imx6_coda.c`, try replacing this line:

    fb_metrics->aligned_frame_height = IMX_VPU_API_ALIGN_VAL_TO(fb_metrics->actual_frame_height, FRAME_LENGTH_ALIGNMENT);

with:

    fb_metrics->aligned_frame_height = IMX_VPU_API_ALIGN_VAL_TO(fb_metrics->actual_frame_height, FRAME_LENGTH_ALIGNMENT);

Then rebuild libimxvpuapi and copy it to your imx6 device.

And tee can indeed cause trouble. It is related to the allocation query. I can check if something can be done there.

**Comment by Donnyp751** [comment] 2022-12-20 18:37
I attempted this with NV12, and I420 without any change in results. Should I make any other changes to my pipeline for debugging?

**Comment by dv1** [comment] 2022-12-20 18:58
Can you post a screenshot?

**Comment by Donnyp751** [comment] 2022-12-20 19:16
![Screenshot from 2022-12-20 13-16-18](https://user-images.githubusercontent.com/16264172/208748503-c597304e-8a8b-4260-998d-6f2c54ee5462.png)

**Comment by dv1** [comment] 2022-12-20 19:17
What resolution is this? Is the greenish bar 8 pixels high?

**Comment by Donnyp751** [comment] 2022-12-20 19:19
40-50 pixels for the green bar shown

**Comment by dv1** [comment] 2022-12-20 19:22
What about this command line:

    GST_DEBUG=2 gst-launch-1.0 imxv4l2videosrc device=/dev/video0 ! imxvpuenc_h264 ! h264parse ! imxvpudec_h264 ! imxg2dvideosink

(Adjust the device node path if necessary.)

**Comment by Donnyp751** [comment] 2022-12-20 20:01
This is with an ov5645 as the video source. 
`/VikingCA/bin # GST_DEBUG=2 gst-launch-1.0 imxv4l2videosrc device=/dev/video0 ! imxvpuenc_h264 ! h264parse ! imxvpudec_h264 ! fakesink
0:00:00.269558333  2030   0x568c20 ERROR     GST_PLUGIN_LOADING gstpluginloader.c:442:gst_plugin_loader_try_helper: Spawning gst-plugin-scanner helper failed: Failed to execute child process “/cross/libexec/gstreamer-1.0/gst-plugin-scanner” (No such file or directory)

(gst-launch-1.0:2030): GStreamer-WARNING **: 15:00:33.677: External plugin loader failed. This most likely means that the plugin loader helper binary was not found or could not be run. You might need to set the GST_PLUGIN_SCANNER environment variable if your setup is unusual. This should normally not be required though.
0:00:00.426369667  2030   0x568c20 WARN      GST_PLUGIN_LOADING gstplugin.c:875:_priv_gst_plugin_load_file_for_registry: module_open failed: /VikingCA/lib/gstreamer-1.0/libgstwebrtc.so: undefined symbol: nice_agent_get_sockets

(gst-launch-1.0:2030): GStreamer-WARNING **: 15:00:33.833: Failed to load plugin '/VikingCA/lib/gstreamer-1.0/libgstwebrtc.so': /VikingCA/lib/gstreamer-1.0/libgstwebrtc.so: undefined symbol: nice_agent_get_sockets
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
[INFO]  ringBufferEnable 0, chromaInterleave 1, mapType 0, linear2TiledEnable 1
[WARN]  VPU iram is less than needed, some parts don't use iram
[INFO]  bitstreamMode 1, chromaInterleave 1, mapType 1, tiled2LinearEnable 0
[INFO]  bitstreamMode 1, chromaInterleave 1, mapType 1, tiled2LinearEnable 0
[WARN]  VPU iram is less than needed, some parts don't use iram
0:00:03.950013001  2030   0x5bbc10 ERROR              imxvpuapi imxvpuapi2_imx6_coda_ipu.c:126:imx_vpu_api_imx6_coda_detile_and_copy_frame_with_ipu_vdoa: queuing IPU task failed: Invalid argument (22)
0:00:03.950374334  2030   0x5bbc10 ERROR              imxvpuapi imxvpuapi2_imx6_coda.c:2518:imx_vpu_api_dec_get_decoded_frame: could not detile and copy decoded frame pixels
0:00:03.950914001  2030   0x5bbc10 ERROR              imxvpudec gstimxvpudec.c:1470:gst_imx_vpu_dec_decode_queued_frames:<imxvpudech264-0> could not retrieve decoded frame: error
0:00:04.015512001  2030   0x5bbc10 ERROR              imxvpuapi imxvpuapi2_imx6_coda_ipu.c:126:imx_vpu_api_imx6_coda_detile_and_copy_frame_with_ipu_vdoa: queuing IPU task failed: Invalid argument (22)
0:00:04.015717001  2030   0x5bbc10 ERROR              imxvpuapi imxvpuapi2_imx6_coda.c:2518:imx_vpu_api_dec_get_decoded_frame: could not detile and copy decoded frame pixels
0:00:04.015939667  2030   0x5bbc10 ERROR              imxvpudec gstimxvpudec.c:1470:gst_imx_vpu_dec_decode_queued_frames:<imxvpudech264-0> could not retrieve decoded frame: error
0:00:04.079675334  2030   0x5bbc10 ERROR              imxvpuapi imxvpuapi2_imx6_coda_ipu.c:126:imx_vpu_api_imx6_coda_detile_and_copy_frame_with_ipu_vdoa: queuing IPU task failed: Invalid argument (22)
0:00:04.079880334  2030   0x5bbc10 ERROR              imxvpuapi imxvpuapi2_imx6_coda.c:2518:imx_vpu_api_dec_get_decoded_frame: could not detile and copy decoded frame pixels
0:00:04.080102001  2030   0x5bbc10 ERROR              imxvpudec gstimxvpudec.c:1470:gst_imx_vpu_dec_decode_queued_frames:<imxvpudech264-0> could not retrieve decoded frame: error
0:00:04.143217334  2030   0x5bbc10 ERROR              imxvpuapi imxvpuapi2_imx6_coda_ipu.c:126:imx_vpu_api_imx6_coda_detile_and_copy_frame_with_ipu_vdoa: queuing IPU task failed: Invalid argument (22)
0:00:04.143423001  2030   0x5bbc10 ERROR              imxvpuapi imxvpuapi2_imx6_coda.c:2518:imx_vpu_api_dec_get_decoded_frame: could not detile and copy decoded frame pixels
0:00:04.143638667  2030   0x5bbc10 ERROR              imxvpudec gstimxvpudec.c:1470:gst_imx_vpu_dec_decode_queued_frames:<imxvpudech264-0> could not retrieve decoded frame: error
0:00:04.206735001  2030   0x5bbc10 ERROR              imxvpuapi imxvpuapi2_imx6_coda_ipu.c:126:imx_vpu_api_imx6_coda_detile_and_copy_frame_with_ipu_vdoa: queuing IPU task failed: Invalid argument (22)
0:00:04.206936667  2030   0x5bbc10 ERROR              imxvpuapi imxvpuapi2_imx6_coda.c:2518:imx_vpu_api_dec_get_decoded_frame: could not detile and copy decoded frame pixels
0:00:04.207227001  2030   0x5bbc10 ERROR              imxvpudec gstimxvpudec.c:1470:gst_imx_vpu_dec_decode_queued_frames:<imxvpudech264-0> could not retrieve decoded frame: error
0:00:04.270724667  2030   0x5bbc10 ERROR              imxvpuapi imxvpuapi2_imx6_coda_ipu.c:126:imx_vpu_api_imx6_coda_detile_and_copy_frame_with_ipu_vdoa: queuing IPU task failed: Invalid argument (22)
0:00:04.270924334  2030   0x5bbc10 ERROR              imxvpuapi imxvpuapi2_imx6_coda.c:2518:imx_vpu_api_dec_get_decoded_frame: could not detile and copy decoded frame pixels
0:00:04.271134001  2030   0x5bbc10 ERROR              imxvpudec gstimxvpudec.c:1470:gst_imx_vpu_dec_decode_queued_frames:<imxvpudech264-0> could not retrieve decoded frame: error
0:00:04.335195001  2030   0x5bbc10 ERROR              imxvpuapi imxvpuapi2_imx6_coda_ipu.c:126:imx_vpu_api_imx6_coda_detile_and_copy_frame_with_ipu_vdoa: queuing IPU task failed: Invalid argument (22)
0:00:04.335393334  2030   0x5bbc10 ERROR              imxvpuapi imxvpuapi2_imx6_coda.c:2518:imx_vpu_api_dec_get_decoded_frame: could not detile and copy decoded frame pixels
0:00:04.335604001  2030   0x5bbc10 ERROR              imxvpudec gstimxvpudec.c:1470:gst_imx_vpu_dec_decode_queued_frames:<imxvpudech264-0> could not retrieve decoded frame: error
0:00:04.375926001  2030   0x5bbc10 ERROR              imxvpuapi imxvpuapi2_imx6_coda.c:2346:imx_vpu_api_dec_decode: internal error; not enough output framebuffers were available even though enough were added prior to decoding
0:00:04.376215667  2030   0x5bbc10 ERROR              imxvpudec gstimxvpudec.c:949:gst_imx_vpu_dec_decode_queued_frames:<imxvpudech264-0> decoding frames failed: error
0:00:04.376651334  2030   0x5bbc10 WARN                 basesrc gstbasesrc.c:3127:gst_base_src_loop:<imxv4l2videosrc0> error: Internal data stream error.
0:00:04.376878667  2030   0x5bbc10 WARN                 basesrc gstbasesrc.c:3127:gst_base_src_loop:<imxv4l2videosrc0> error: streaming stopped, reason error (-5)
ERROR: from element /GstPipeline:pipeline0/GstImxV4L2VideoSrc:imxv4l2videosrc0: Internal data stream error.
Additional debug info:
../subprojects/gstreamer/libs/gst/base/gstbasesrc.c(3127): gst_base_src_loop (): /GstPipeline:pipeline0/GstImxV4L2VideoSrc:imxv4l2videosrc0:
streaming stopped, reason error (-5)
0:00:04.378842001  2030   0x5bbc10 WARN            videodecoder gstvideodecoder.c:1418:gst_video_decoder_sink_event_default:<imxvpudech264-0> error: No valid frames decoded before end of stream
Execution ended after 0:00:02.626352334
Setting pipeline to NULL ...
0:00:04.379069334  2030   0x5bbc10 WARN            videodecoder gstvideodecoder.c:1418:gst_video_decoder_sink_event_default:<imxvpudech264-0> error: no valid frames found
ERROR: from element /GstPipeline:pipeline0/GstImxVpuDecH264:imxvpudech264-0: No valid frames decoded before end of stream
Additional debug info:
../subprojects/gst-plugins-base/gst-libs/gst/video/gstvideodecoder.c(1418): gst_video_decoder_sink_event_default (): /GstPipeline:pipeline0/GstImxVpuDecH264:imxvpudech264-0:
no valid frames found
Freeing pipeline ...`

**Comment by Donnyp751** [comment] 2022-12-20 20:03
I've never seen the decoder errors, I only have used the encoder on the device. This is with the change you recommended above.
`fb_metrics->aligned_frame_height = IMX_VPU_API_ALIGN_VAL_TO(fb_metrics->actual_frame_height, 8);`

**Comment by dv1** [comment] 2022-12-20 20:07
The decoder error is caused by a kernel bug. I reported it here: https://github.com/Freescale/meta-freescale/issues/1337

If you have one of the `openh264dec` or `avdec_h264` GStreamer elements installed, try replacing `imxvpudec_h264` with those. Right now, the way to get `imxvpudec` to work is to use `linux-imx` instead of `linux-fslc-imx`,  but that is more involved, and for trying out this problem, it is not necessary.

Also,  instead of using 8 as aligned, try 2 :

```
fb_metrics->aligned_frame_height = IMX_VPU_API_ALIGN_VAL_TO(fb_metrics->actual_frame_height, 8);
```

**Comment by Donnyp751** [comment] 2022-12-20 20:12
I will rebuild, and rerun the command and post the results shortly. Is that specific sink needed or can I just fakesink it?

**Comment by dv1** [comment] 2022-12-20 20:14
Well, the point is to see if the decoded frame shows that color bar. But if you have no connected HDMI screen, you can also do: 

`GST_DEBUG="2,*v4l*:9,*vpu*:9" gst-launch-1.0 -e imxv4l2videosrc device=/dev/video0 ! imxvpuenc_h264 ! h264parse ! avdec_h264 ! videoconvert ! jpegenc snapshot=true ! filesink location=snapshot.jpg`

This grabs exactly one frame, writes it to `snapshot.jpg`, and then stops the pipeline.

**Comment by Donnyp751** [comment] 2022-12-20 20:15
Gotcha, yeah I can run that. I usually just send to udpsink to my dev machine for testing.

**Comment by Donnyp751** [comment] 2022-12-20 20:52
![snapshot](https://user-images.githubusercontent.com/16264172/208763926-f5431a80-fdf5-4393-9ffd-25256345ee06.jpg)
Here's with the 2 instead of 8, and the pipeline you provided above. 
[log.txt](https://github.com/Freescale/libimxvpuapi/files/10272603/log.txt)

**Comment by dv1** [comment] 2022-12-20 21:38
I do not have an ov5645 module. But this is strange. I can replicate this exact problem if I don't add the alignment change. If I do, the problem is completely gone. Can you double check that the new version - the one with height alignment set to 2 - is really being used? Add this line right next to the alignment change: `IMX_VPU_API_LOG("this is the new version");` and then produce a log file with the `GST_DEBUG="2,*v4l*:9,*vpu*:9"` log level.

**Comment by Donnyp751** [comment] 2022-12-20 22:07
I may have modified the wrong call of it. Just noticed that there is two instances of the line you sent me, and I modified the decoder function one, not the enc side. Retrying

**Comment by Donnyp751** [comment] 2022-12-20 22:14
Sweet, so changing to 8 for the height solved the green line issue. The framerate is still dropping when there is a tee in the pipeline, but other then that it appears to be functioning similar to before the rewrite.

**Comment by dv1** [comment] 2022-12-20 22:20
Can you provide a gst-launch line that shows the tee issue?

**Comment by Donnyp751** [comment] 2022-12-20 22:29
imx6 side
gst-launch-1.0 -e imxv4l2videosrc device=/dev/video0 ! queue ! tee name=t t. ! queue ! imxvpuenc_h264 bitrate=500 ! rtph264pay ! udpsink host=192.168.x.x port=5004 sync=false t. ! queue ! imxvpuen
c_h264 bitrate=500 ! rtph264pay ! udpsink host=192.168.x.x port=6004

recv side
gst-launch-1.0 -vm udpsrc port=5004 address=0.0.0.0 ! application/x-rtp, clock-rate=90000,payload=96 ! rtph264depay ! h264parse  ! openh264dec ! fpsdisplaysink sync=false

**Comment by dv1** [comment] 2022-12-20 22:30
Be aware that 1080p frames put a considerable strain on the imx6. Did such a tee pipeline work with the old libimxvpuapi, or is this something entirely new?

**Comment by Donnyp751** [comment] 2022-12-20 22:38
I just noticed, if I run 
gst-launch-1.0 -e imxv4l2videosrc device=/dev/video0 ! queue ! tee name=t t. ! queue ! imxvpuenc_h264 bitrate=500 ! rtph264pay ! udpsink host=192.168.210.26 port=5004 sync=false t. ! fakesink
The one stream stays at 30fps, so maybe it's an issue having two encoders?
I was previously running two streams but had similar fps fluctuations at 1080p. This was something new trying to get them both to work at 1080P as I was under the impression it could handle two 1080p streams at 30 fps.

**Comment by Donnyp751** [comment] 2022-12-20 22:39
Also running the dual stream pipeline @ 1080P 20fps it's averaging only 5% CPU, so I wasn't thinking it was a cpu strain issue.

**Comment by dv1** [comment] 2022-12-20 22:40
But did you have two simultaneous 1080p30 encodings going on with the old gstreamer-imx and old libimxvpuapi?

2x that signal hits the limits of the bandwidth on an imx6, which is why I ask about the old versions.

**Comment by Donnyp751** [comment] 2022-12-20 22:41
No I did not, It would bounce around from 12-20.

**Comment by dv1** [comment] 2022-12-20 22:42
If you consult the reference manual, you'll see that two 1080p30 encodings on the imx6 are tough to do. This most likely requires overclocking. Note for example how _decoding_ a single 1080p stream that goes beyond ~30 fps gets tricky as well.

**Comment by dv1** [comment] 2022-12-20 22:44
To verify this, can you add `! video/x-raw,width=720p !' in between the imxv4l2videosrc and the queue elements?

**Comment by Donnyp751** [comment] 2022-12-20 22:50
Ahh I misunderstood when I was going through the manual before. I was under the impression that all the supported resolutions could run a dual stream at that rate. 

Yes, It looks like it runs 30 fps at 720. I will just have to work around that as a known limitation. Is this a problem on the newer imx platforms like the imx 8?

**Comment by dv1** [comment] 2022-12-20 22:52
I did not try it yet, but I think the imx8m mini's H1 encoder can do dual 1080p30 encoding. I will try it out. Be aware though that not all imx8 variants have encoders. I am aware of the imx8m mini (Hantro H1 encoder), imx8m plus (VC8000E encoder), imx8 quadmax and quadxplus (amphion windsor encoder).

**Comment by Donnyp751** [comment] 2022-12-20 22:53
Yeah I had seen some only support software encoding. Any recommendations on more capable SOM's similar to the imx6?

**Comment by dv1** [comment] 2022-12-20 22:55
I will check the imx8m mini and get back at you.

**Comment by jnettlet** [comment] 2022-12-21 06:04
> If you consult the reference manual, you'll see that two 1080p30 encodings on the imx6 are tough to do. This most likely requires overclocking. Note for example how _decoding_ a single 1080p stream that goes beyond ~30 fps gets tricky as well. EDIT: I ping @jnettlet , since I think he did overclock an imx6 once for 1080p60 decoding.

to do more than 1080p at 40fps you need to overclock the VPU. The default overclock is 352Mhz but I found that the clock settings in this patch were stable and able to provide 1080p60 https://github.com/SolidRun/linux-stable/commit/787f005d7d28ea9bb926241e0bb96fa65fcb1d2f

**Comment by Donnyp751** [comment] 2022-12-21 06:30
> > If you consult the reference manual, you'll see that two 1080p30 encodings on the imx6 are tough to do. This most likely requires overclocking. Note for example how _decoding_ a single 1080p stream that goes beyond ~30 fps gets tricky as well. EDIT: I ping @jnettlet , since I think he did overclock an imx6 once for 1080p60 decoding.
> 
> to do more than 1080p at 40fps you need to overclock the VPU. The default overclock is 352Mhz but I found that the clock settings in this patch were stable and able to provide 1080p60 [SolidRun/linux-stable@787f005](https://github.com/SolidRun/linux-stable/commit/787f005d7d28ea9bb926241e0bb96fa65fcb1d2f)

With the patch you linked to, not using the CONFIG_MX6_VPU_352M build config would overclock the vpu from the default 266?

**Comment by jnettlet** [comment] 2022-12-21 06:32
Yes, we use that as our default clocking since we found it to be 100%
stable.

**Comment by dv1** [comment] 2022-12-27 17:36
The original issue is fixed, and the followup posts are a different topic. Closing this now. Feel free to reopen if needed.

**Closed by dv1** 2022-12-27 17:36 UTC

**Comment by Donnyp751** [comment] 2023-02-06 14:47
@dv1 I'm not sure if this is related, but with the change it seems that now a green visual effect starts from the top every second, and gets a little worse with each frame until the frame is refreshed. At the default gop-size of 16 it's flashing at approx 1.5-2 hz, on just the top 50 pixels. But if you increase the gop-size to like 100 or so you can see the green spread further down the image over a few seconds before getting the new frame and resetting to a clean image. 
screenshot from the start, and another towards the end of a cycle.

Should I create a new ticket for this or is it related? Didn't see this prior to changing the 

![Screenshot from 2023-02-06 08-34-05](https://user-i
![Screenshot from 2023-02-06 08-34-32](https://user-images.githubusercontent.com/16264172/216999255-d3345603-9301-4645-be4d-9800e865519b.png)
mages.githubusercontent.com/16264172/216999112-4a6c34a4-1caf-46a1-b780-2fc51cbd7f80.png)
